namespace: papyrus

deployment:
  name: papyrusbot
  image: ghcr.io/preparingforexams/papyrusbot:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: papyrusbot
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 300m
    memory: 300Mi
  updateStrategy: Recreate

secret:
  name: papyrusbot
  botToken: __TELEGRAM_TOKEN__

configmap:
  name: papyrusbot
  apiBaseUrl: "http://papyrusapi"
  apiBasePath: "api"
