apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  API_BASE_URL: {{ .Values.configmap.apiBaseUrl }}
  API_BASE_PATH: {{ .Values.configmap.apiBasePath }}
